// <auto-generated />
namespace Estrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SequenciaInProductTreeTo2Chars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SequenciaInProductTreeTo2Chars));
        
        string IMigrationMetadata.Id
        {
            get { return "201709231857411_SequenciaInProductTreeTo2Chars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
